name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.2
    - name: Set up JDK 17
      uses: actions/setup-java@v3.11.0
      with:
        java-version: 17
        distribution: adopt
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew shadowJar
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: JEXT-Reborn_${{ github.sha }}
        path: build/libs/*.jar

  publishDocs:
    needs: build

    if: ${{ false }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.2
      - name: Set up JDK 17
        uses: actions/setup-java@v3.11.0
        with:
          java-version: 17
          distribution: adopt
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build docs with Gradle
        run: ./gradlew dokkaHtml
        env:
          githubTag: ${{ github.ref }}
